#pragma once
#include "quanCo.h"

bool nhapBC(quanCo* BC[][8]);
void nhapBCMacDinh(quanCo* BC[][8]);
void xuatBC(quanCo* BC[][8]);
void xuatBCBinhThuong(quanCo* BC[][8]);
void xuatBCDaChon(int x, char y, quanCo* BC[][8]);
void xuatBCDaDiChuyen(int x, char y, quanCo* BC[][8]);
bool kiemTraAn(int x, int y, int xNew, int yNew, quanCo* BC[][8]);
bool getMau(int x, int y, quanCo* BC[][8]);
bool getQuanCo(int x, int y, quanCo* BC[][8]);
void setQuanCo(int x, char y, int xNew, char yNew, quanCo*& A, quanCo* BC[][8]);
void resetQuanCo(int x, char y, int xNew, char yNew, quanCo*& A, quanCo* BC[][8]);
void nhapThanh(int x, int y, int xNew, int yNew, quanCo* BC[][8]);
void phong(int x, int y, int xNew, int yNew, quanCo* BC[][8]);
void batChotQuaDuong(int x, int y, int xNew, int yNew, quanCo*& A, quanCo* BC[][8]);
bool kiemTraNuocDi(int x, int y, int xNew, int yNew, quanCo* BC[][8]);
void diChuyen(int x, char y, int& xv, int& yv, bool luot, int xNew, char yNew, int& xd, char& yd, quanCo*& A, quanCo* BC[][8]);
bool kiemTraNuocDiChot(int x, int y, int xNew, int yNew, quanCo* BC[][8]);
bool kiemTraNuocDiXe(int x, int y, int xNew, int yNew, quanCo* BC[][8]);
bool kiemTraNuocDiMa(int x, int y, int xNew, int yNew, quanCo* BC[][8]);
bool kiemTraNuocDiTuong(int x, int y, int xNew, int yNew, quanCo* BC[][8]);
bool kiemTraNuocDiHau(int x, int y, int xNew, int yNew, quanCo* BC[][8]);
bool kiemTraNuocDiVua(int x, int y, int xNew, int yNew, quanCo* BC[][8]);
void diChuyenChot(int x, int y, int xNew, int yNew, quanCo*& A, quanCo* BC[][8]);
void diChuyenXe(int x, int y, int xNew, int yNew, quanCo*& A, quanCo* BC[][8]);
void diChuyenMa(int x, int y, int xNew, int yNew, quanCo*& A, quanCo* BC[][8]);
void diChuyenTuong(int x, int y, int xNew, int yNew, quanCo*& A, quanCo* BC[][8]);
void diChuyenHau(int x, int y, int xNew, int yNew, quanCo*& A, quanCo* BC[][8]);
void diChuyenVua(int x, int y, int xNew, int yNew, quanCo*& A, quanCo* BC[][8]);
bool kiemTraChieu(int x, int y, quanCo* BC[][8]);
bool kiemTraChieu3(int x, int y, quanCo* BC[][8]);
bool kiemTraChieuXungQuanh(int x, int y, quanCo* BC[][8]);
bool kiemTraChieuBi(int x, int y, quanCo* BC[][8]);
bool kiemTraChieu2(int x, int y, int& xC, int& yC, char& bC, quanCo* BC[][8]);
bool kiemTraQuanCo(bool luot, quanCo* BC[][8]);
bool kiemTraCoHoa(int x, int y, quanCo* BC[][8]);
void timVua(int& xv, int& yv, bool luot, quanCo* BC[][8]);
void setConsoleTextColor(int text);
void setConsoleBackgroundColor(int background);
void nuocDiChot(int x, char y, quanCo* BC[][8], quanCo* bc[][8]);
void nuocDiXe(int x, char y, quanCo* BC[][8], quanCo* bc[][8]);
void nuocDiMa(int x, char y, quanCo* BC[][8], quanCo* bc[][8]);
void nuocDiTuong(int x, char y, quanCo* BC[][8], quanCo* bc[][8]);
void nuocDiHau(int x, char y, quanCo* BC[][8], quanCo* bc[][8]);
void nuocDiVua(int x, char y, quanCo* BC[][8], quanCo* bc[][8]);
void kiemTraNuocDi(int x, char y, quanCo* BC[][8], quanCo* bc[][8]);